enum ActionTypesCart {
  UPDATE_SHIPPING = 'UPDATE_SHIPPING',
  UPDATE_SECTION = 'UPDATE_SECTION',
  UPDATE_SHIPPING_STATUS = 'UPDATE_SHIPPING_STATUS',
  UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS',
  UPDATE_PICKUP_ADDRESS = 'UPDATE_PICKUP_ADDRESS',
  UPDATE_SHIPPING_WAY = 'UPDATE_SHIPPING_WAY',
  UPDATE_PAYMENT = 'UPDATE_PAYMENT',
  UPDATE_BILLING_ADDRESS = 'UPDATE_BILLING_ADDRESS',
  UPDATE_CARD = 'UPDATE_CARD',
  RESET_INFO = 'RESET_INFO',
  UPDATE_PROVIDER = 'UPDATE_PROVIDER',
  UPDATE_PAYMENT_STATUS = 'UPDATE_PAYMENT_STATUS',
  UPDATE_DELIVERY = 'UPDATE_DELIVERY',
  UPDATE_DELIVERY_STATUS = 'UPDATE_DELIVERY_STATUS',
  UPDATE_DELIVERY_INFO = 'UPDATE_DELIVERY_INFO',

  SET_PICKUP_LOCATIONS = 'SET_PICKUP_LOCATIONS',
  SET_DELIVERY_RATES = 'SET_DELIVERY_RATES',
  SET_PAYMENT_PROVIDERS = 'SET_PAYMENT_PROVIDERS',
  SET_COUNTRIES = 'SET_COUNTRIES',
}

export default ActionTypesCart;
