import ActionTypesDesigner from './designerStore/actionTypes';

enum ActionTypesSite {
  INIT_APP_STORE = 'INIT_APP_STORE',
  INIT_HOMEPAGE_STORE = 'INIT_HOMEPAGE_STORE',
  INIT_PRODUCT_PAGE_STORE = 'INIT_PRODUCT_PAGE_STORE',
  INIT_PRODUCTGROUP_PAGE_STORE = 'INIT_PRODUCTGROUP_PAGE_STORE',

  SET_PRODUCTGROUP_PAGE_SELECTOR = 'SET_PRODUCTGROUP_PAGE_SELECTOR',

  SET_SESSION_CONFIG = 'SET_SESSION_CONFIG',

  UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS',

  RESET_STATE = 'RESET_STATE',

  UPDATE_TESTIMONIALS = 'UPDATE_TESTIMONIALS',
  UPDATE_SOCIAL_LINKS = 'UPDATE_SOCIAL_LINKS',
  UPDATE_SUPPORT_SCRIPTS = 'UPDATE_SUPPORT_SCRIPTS',
  UPDATE_MENU = 'UPDATE_MENU',
  UPDATE_RECOMMENDED = 'UPDATE_RECOMMENDED',
}

const ActionTypes = { Designer: ActionTypesDesigner, ...ActionTypesSite };

export default ActionTypes;
