enum ActionTypesCart {
  SET_ACTIVE_THEME = 'SET_ACTIVE_THEME',
  SET_THEMES_SIDES = 'SET_THEMES_SIDES',
  SET_ACTIVE_THEME_SIDE = 'SET_ACTIVE_THEME_SIDE',
  UPDATE_SEARCH = 'UPDATE_SEARCH',
  UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS',
  INIT_THEMES_PAGE_STORE = 'INIT_THEMES_PAGE_STORE',
  INIT_THEMES_CARDS = 'INIT_THEMES_CARDS',
  UPDATE_THEMES_CARDS = 'UPDATE_THEMES_CARDS',
}

export default ActionTypesCart;
